### ISSUE TITLE
[BUG] Width (400) and height (0) cannot be <= 0

### ISSUE THREAD

**Issue by duraki** [Battelle/cantordust#3] opened 2020-07-25 08:56 UTC
Installed and opened blob with Ghidra. The file is raw XML file. The graphview is visible but error message still pops up each time I run the script.

```
Uncaught Exception! 
IllegalArgumentException - Width (400) and height (0) cannot be <= 0
java.lang.IllegalArgumentException: Width (400) and height (0) cannot be <= 0
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:324)
	at BitMapSliderUI.makeBitmap(BitMapSliderUI.java:106)
	at BitMapSliderUI.lambda$new$0(BitMapSliderUI.java:41)
	at java.base/java.lang.Thread.run(Thread.java:834)

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: C:\Program Files\Amazon Corretto\jdk11.0.7_10
JVM Version: Amazon.com Inc. 11.0.7
OS: Windows 10 10.0 amd64
Workstation: hostname
```

See image below:

<img width="831" alt="2020-07-25 10_54_45-e" src="https://user-images.githubusercontent.com/5892610/88453235-6503fb80-ce65-11ea-8ece-247d8e1444a2.png">

**Comment by sengi12** [comment] 2020-07-25 13:42
Hi duraki, thanks for bringing this to our attention. I believe I may know what the issue is, but I will have to look more into it to be sure. 

Any chance you could share the size of the file you had opened in Ghidra?

**Comment by duraki** [comment] 2020-07-25 16:32
Hi @sengi12, you are welcome. I suppose you ask about file size, right? If so;

```
PS C:\> ls
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         6/19/2020  10:38 AM            763 blob.xml
```

**Comment by sengi12** [comment] 2020-10-15 16:26
@duraki I apologize for the delay as I've been quite preoccupied with school. I think I fixed your issue though as I was able to recreate it in a Windows VM and isolated the issue to a couple lines within BitMapSliderUI.java. It simply had to do with the file being so small that some math was done incorrectly. It should work now though!

**Comment by Battelle-Cyber-34** [comment] 2020-10-15 17:50
Should be fixed in latest merge.

**Closed by Battelle-Cyber-34** 2020-10-15 17:50 UTC

**Comment by duraki** [comment] 2020-10-16 06:48
Awesome! Thanks a lot for PR.
